import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer"
import About from '@/Pages/Userside/About/About';
import FAQ from '@/Pages/Userside/FAQ/FAQ';
import Privacy from '../Pages/Userside/Terms-&-privacy/Privacy'
import Page404 from '@/Pages/Userside/404pages/page404';
import LegalManagement from '@/Pages/Userside/LegalManagement/LegalManagement';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className="">       <Navbar />
        <LegalManagement/>
        {/* <About /> */}
        {/* <FAQ /> */}
        {/* <Privacy/> */}
        {/* <Page404/> */}
        {/* <Footer /> */}
        </div> 
        </body>
    </html>
  )
}
